#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 5424026
#
# Source0 file verified with key 0x17280A9781186ACF (mathieu.desnoyers@efficios.com)
#
Name     : userspace-rcu
Version  : 0.15.0
Release  : 15
URL      : https://www.lttng.org/files/urcu/userspace-rcu-0.15.0.tar.bz2
Source0  : https://www.lttng.org/files/urcu/userspace-rcu-0.15.0.tar.bz2
Source1  : https://www.lttng.org/files/urcu/userspace-rcu-0.15.0.tar.bz2.asc
Source2  : 17280A9781186ACF.pkey
Summary  : A userspace RCU (read-copy-update) library, membarrier syscall version
Group    : Development/Tools
License  : BSD-2-Clause CC0-1.0 FSFAP GPL-2.0 LGPL-2.1 MIT
Requires: userspace-rcu-lib = %{version}-%{release}
Requires: userspace-rcu-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : gnupg
BuildRequires : grep
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<!--
SPDX-License-Identifier: CC-BY-4.0
-->
Userspace RCU Implementation
============================

%package dev
Summary: dev components for the userspace-rcu package.
Group: Development
Requires: userspace-rcu-lib = %{version}-%{release}
Provides: userspace-rcu-devel = %{version}-%{release}
Requires: userspace-rcu = %{version}-%{release}

%description dev
dev components for the userspace-rcu package.


%package doc
Summary: doc components for the userspace-rcu package.
Group: Documentation

%description doc
doc components for the userspace-rcu package.


%package lib
Summary: lib components for the userspace-rcu package.
Group: Libraries
Requires: userspace-rcu-license = %{version}-%{release}

%description lib
lib components for the userspace-rcu package.


%package license
Summary: license components for the userspace-rcu package.
Group: Default

%description license
license components for the userspace-rcu package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 17280A9781186ACF' gpg.status
%setup -q -n userspace-rcu-0.15.0
cd %{_builddir}/userspace-rcu-0.15.0
pushd ..
cp -a userspace-rcu-0.15.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735117529
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735117529
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/userspace-rcu
cp %{_builddir}/userspace-rcu-%{version}/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/userspace-rcu/07c1ab270255cf247438e2358ff0c18835b6a6ce || :
cp %{_builddir}/userspace-rcu-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/userspace-rcu/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/userspace-rcu-%{version}/LICENSES/FSFAP.txt %{buildroot}/usr/share/package-licenses/userspace-rcu/da20b47077b3106fb65720d6fef309f39043fa60 || :
cp %{_builddir}/userspace-rcu-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/userspace-rcu/3cb34cfc72e87654683f2894299adf912d14b284 || :
cp %{_builddir}/userspace-rcu-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/userspace-rcu/3cb34cfc72e87654683f2894299adf912d14b284 || :
cp %{_builddir}/userspace-rcu-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/userspace-rcu/fa05e58320cb7c64786b26396f4b992579a628bc || :
cp %{_builddir}/userspace-rcu-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/userspace-rcu/fa05e58320cb7c64786b26396f4b992579a628bc || :
cp %{_builddir}/userspace-rcu-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/userspace-rcu/adadb67a9875aeeac285309f1eab6e47d9ee08a7 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/urcu-bp.h
/usr/include/urcu-call-rcu.h
/usr/include/urcu-defer.h
/usr/include/urcu-flavor.h
/usr/include/urcu-pointer.h
/usr/include/urcu-qsbr.h
/usr/include/urcu.h
/usr/include/urcu/annotate.h
/usr/include/urcu/arch.h
/usr/include/urcu/arch/aarch64.h
/usr/include/urcu/arch/alpha.h
/usr/include/urcu/arch/arm.h
/usr/include/urcu/arch/gcc.h
/usr/include/urcu/arch/generic.h
/usr/include/urcu/arch/hppa.h
/usr/include/urcu/arch/ia64.h
/usr/include/urcu/arch/loongarch.h
/usr/include/urcu/arch/m68k.h
/usr/include/urcu/arch/mips.h
/usr/include/urcu/arch/nios2.h
/usr/include/urcu/arch/ppc.h
/usr/include/urcu/arch/riscv.h
/usr/include/urcu/arch/s390.h
/usr/include/urcu/arch/sparc64.h
/usr/include/urcu/arch/tile.h
/usr/include/urcu/arch/x86.h
/usr/include/urcu/assert.h
/usr/include/urcu/call-rcu.h
/usr/include/urcu/cds.h
/usr/include/urcu/compiler.h
/usr/include/urcu/config.h
/usr/include/urcu/debug.h
/usr/include/urcu/defer.h
/usr/include/urcu/flavor.h
/usr/include/urcu/futex.h
/usr/include/urcu/hlist.h
/usr/include/urcu/lfstack.h
/usr/include/urcu/list.h
/usr/include/urcu/map/clear.h
/usr/include/urcu/map/urcu-bp.h
/usr/include/urcu/map/urcu-mb.h
/usr/include/urcu/map/urcu-memb.h
/usr/include/urcu/map/urcu-qsbr.h
/usr/include/urcu/map/urcu.h
/usr/include/urcu/pointer.h
/usr/include/urcu/rcuhlist.h
/usr/include/urcu/rculfhash.h
/usr/include/urcu/rculfqueue.h
/usr/include/urcu/rculfstack.h
/usr/include/urcu/rculist.h
/usr/include/urcu/ref.h
/usr/include/urcu/static/lfstack.h
/usr/include/urcu/static/pointer.h
/usr/include/urcu/static/rculfqueue.h
/usr/include/urcu/static/rculfstack.h
/usr/include/urcu/static/urcu-bp.h
/usr/include/urcu/static/urcu-common.h
/usr/include/urcu/static/urcu-mb.h
/usr/include/urcu/static/urcu-memb.h
/usr/include/urcu/static/urcu-qsbr.h
/usr/include/urcu/static/urcu.h
/usr/include/urcu/static/wfcqueue.h
/usr/include/urcu/static/wfqueue.h
/usr/include/urcu/static/wfstack.h
/usr/include/urcu/syscall-compat.h
/usr/include/urcu/system.h
/usr/include/urcu/tls-compat.h
/usr/include/urcu/uatomic.h
/usr/include/urcu/uatomic/aarch64.h
/usr/include/urcu/uatomic/alpha.h
/usr/include/urcu/uatomic/api.h
/usr/include/urcu/uatomic/arm.h
/usr/include/urcu/uatomic/builtins-generic.h
/usr/include/urcu/uatomic/builtins.h
/usr/include/urcu/uatomic/gcc.h
/usr/include/urcu/uatomic/generic.h
/usr/include/urcu/uatomic/hppa.h
/usr/include/urcu/uatomic/ia64.h
/usr/include/urcu/uatomic/loongarch.h
/usr/include/urcu/uatomic/m68k.h
/usr/include/urcu/uatomic/mips.h
/usr/include/urcu/uatomic/nios2.h
/usr/include/urcu/uatomic/ppc.h
/usr/include/urcu/uatomic/riscv.h
/usr/include/urcu/uatomic/s390.h
/usr/include/urcu/uatomic/sparc64.h
/usr/include/urcu/uatomic/tile.h
/usr/include/urcu/uatomic/x86.h
/usr/include/urcu/uatomic_arch.h
/usr/include/urcu/urcu-bp.h
/usr/include/urcu/urcu-futex.h
/usr/include/urcu/urcu-mb.h
/usr/include/urcu/urcu-memb.h
/usr/include/urcu/urcu-poll.h
/usr/include/urcu/urcu-qsbr.h
/usr/include/urcu/urcu.h
/usr/include/urcu/urcu_ref.h
/usr/include/urcu/wfcqueue.h
/usr/include/urcu/wfqueue.h
/usr/include/urcu/wfstack.h
/usr/lib64/liburcu-bp.so
/usr/lib64/liburcu-cds.so
/usr/lib64/liburcu-common.so
/usr/lib64/liburcu-mb.so
/usr/lib64/liburcu-memb.so
/usr/lib64/liburcu-qsbr.so
/usr/lib64/liburcu.so
/usr/lib64/pkgconfig/liburcu-bp.pc
/usr/lib64/pkgconfig/liburcu-cds.pc
/usr/lib64/pkgconfig/liburcu-mb.pc
/usr/lib64/pkgconfig/liburcu-memb.pc
/usr/lib64/pkgconfig/liburcu-qsbr.pc
/usr/lib64/pkgconfig/liburcu.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/userspace\-rcu/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/liburcu-bp.so.8.1.0
/V3/usr/lib64/liburcu-cds.so.8.1.0
/V3/usr/lib64/liburcu-common.so.8.1.0
/V3/usr/lib64/liburcu-mb.so.8.1.0
/V3/usr/lib64/liburcu-memb.so.8.1.0
/V3/usr/lib64/liburcu-qsbr.so.8.1.0
/V3/usr/lib64/liburcu.so.8.1.0
/usr/lib64/liburcu-bp.so.8
/usr/lib64/liburcu-bp.so.8.1.0
/usr/lib64/liburcu-cds.so.8
/usr/lib64/liburcu-cds.so.8.1.0
/usr/lib64/liburcu-common.so.8
/usr/lib64/liburcu-common.so.8.1.0
/usr/lib64/liburcu-mb.so.8
/usr/lib64/liburcu-mb.so.8.1.0
/usr/lib64/liburcu-memb.so.8
/usr/lib64/liburcu-memb.so.8.1.0
/usr/lib64/liburcu-qsbr.so.8
/usr/lib64/liburcu-qsbr.so.8.1.0
/usr/lib64/liburcu.so.8
/usr/lib64/liburcu.so.8.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/userspace-rcu/07c1ab270255cf247438e2358ff0c18835b6a6ce
/usr/share/package-licenses/userspace-rcu/3cb34cfc72e87654683f2894299adf912d14b284
/usr/share/package-licenses/userspace-rcu/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/userspace-rcu/adadb67a9875aeeac285309f1eab6e47d9ee08a7
/usr/share/package-licenses/userspace-rcu/da20b47077b3106fb65720d6fef309f39043fa60
/usr/share/package-licenses/userspace-rcu/fa05e58320cb7c64786b26396f4b992579a628bc
